language: go
install:
  - go get code.google.com/p/goprotobuf/proto
  - go get github.com/crhym3/aegot/aet
  - $GOPATH/bin/aet init
script:
  - "cd $TRAVIS_BUILD_DIR && $GOPATH/bin/aet test ./endpoints"
