language: go
install:
  - curl -sSo gae_sdk.zip https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_linux_amd64-1.9.12.zip
  - unzip gae_sdk.zip
script:
  - ./go_appengine/goapp -v test ./endpoints
